CREATE OR REPLACE PROCEDURE SP_EXECUTE_DDL_IF_EXISTS(OBJTYPE VARCHAR, OBJSCHEMA VARCHAR, OBJNAME VARCHAR, 
	DDLSTATEMENT VARCHAR) 
AUTHID CURRENT_USER IS
BEGIN
  DECLARE V_CNT NUMBER;
BEGIN
    SELECT COUNT(*) 
      INTO V_CNT 
      FROM ALL_OBJECTS
     WHERE OWNER = OBJSCHEMA
       AND OBJECT_NAME = OBJNAME
       AND OBJECT_TYPE = OBJTYPE;
IF V_CNT > 0 THEN 
        EXECUTE IMMEDIATE(DDLSTATEMENT);
END IF;
END;
END;
/

CREATE OR REPLACE PROCEDURE SP_CREATE_TABLE(TABLESCHEMA VARCHAR, TABLENAME VARCHAR, 
    DDLSTATEMENT VARCHAR)
AUTHID CURRENT_USER IS
BEGIN
  DECLARE vCreateTrigger VARCHAR2(2000);
BEGIN
  EXECUTE IMMEDIATE(DDLSTATEMENT);
  vCreateTrigger := 'create or replace trigger ' || TABLESCHEMA || '.' || TABLENAME || '_TRIG ' ||
                   'BEFORE INSERT OR UPDATE OR DELETE ON ' || TABLESCHEMA || '.' || TABLENAME ||
                   ' FOR EACH ROW ' ||
                   'BEGIN ' ||
                   'INSERT INTO ' || TABLESCHEMA || '.TRIGGERED_DML_STATEMENTS VALUES(''' || TABLESCHEMA || ''',''' ||
                   TABLENAME || ''',SYSDATE); ' ||
                   'END;';
  DBMS_OUTPUT.PUT_LINE(vCreateTrigger);
  EXECUTE IMMEDIATE(vCreateTrigger);
END;
END;
/

create or replace trigger CDCDEMOA.PROD6_TRIG BEFORE INSERT OR UPDATE OR DELETE ON CDCDEMOA.PROD6
FOR EACH ROW
BEGIN
INSERT INTO CDCDEMOA.TRIGGERED_DML_STATEMENTS
VALUES('CDCDEMOA','PROD6',SYSDATE);
END;
/

