-- Stored procedure to execute a DDL statement only if the object exists
CREATE OR REPLACE PROCEDURE SP_EXECUTE_DDL_IF_EXISTS(OBJTYPE VARCHAR, OBJSCHEMA VARCHAR, OBJNAME VARCHAR, 
	DDLSTATEMENT VARCHAR) 
AUTHID CURRENT_USER IS
BEGIN
  DECLARE V_CNT NUMBER;
BEGIN
    SELECT COUNT(*) 
      INTO V_CNT 
      FROM ALL_OBJECTS
     WHERE OWNER = OBJSCHEMA
       AND OBJECT_NAME = OBJNAME
       AND OBJECT_TYPE = OBJTYPE;
IF V_CNT > 0 THEN 
        EXECUTE IMMEDIATE(DDLSTATEMENT);
END IF;
END;
END;
/

-- Table that holds DDL statements to be executed after the table has been created
CREATE TABLE CREATE_TABLE_POST_DDL (TABLESCHEMA VARCHAR2(32), TABLENAME VARCHAR2(32), EXECSEQ INT, 
  DDLSTATEMENT VARCHAR2(4000), 
  CONSTRAINT CREATE_TABLE_POST_DDL_PK PRIMARY KEY (TABLESCHEMA, TABLENAME, EXECSEQ));
  
-- Stored procedure which will be invoked after a CREATE TABLE statement
-- The stored procedure executes a sequence of DDL statements kept in the CREATE_TABLE_POST_DDL table in
-- the CDC metadata schema
CREATE OR REPLACE PROCEDURE SP_CREATE_TABLE(pCDC_SCHEMA VARCHAR, pTABLE_SCHEMA VARCHAR, pTABLE_NAME VARCHAR)
AUTHID CURRENT_USER IS
  vDDL_STATEMENT VARCHAR2(4000);
  TYPE cursor_type IS REF CURSOR;
  c2 cursor_type;
BEGIN
  OPEN c2 for 'SELECT DDLSTATEMENT FROM ' || pCDC_SCHEMA || '.CREATE_TABLE_POST_DDL WHERE TABLESCHEMA=''' 
       || pTABLE_SCHEMA || ''' AND TABLENAME=''' || pTABLE_NAME || ''' ORDER BY EXECSEQ';
  LOOP
    FETCH c2 INTO vDDL_STATEMENT;
    EXIT WHEN c2%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('POST CREATE DDL statement: ' || vDDL_STATEMENT);
    EXECUTE IMMEDIATE(vDDL_STATEMENT);
  END LOOP;
  CLOSE c2;
END;
/


